# Introduction {#intro}

Imagine que usted es un chef, y como tal disfruta enormemente del arte de la cocina. Como amante de la cocina, cada vez que alguna celebración especial se avecina, es su tradición el preparar sus mejores recetas para sus seres queridos. Sin embargo, en esta ocación en particular, la celebración se llevará a cabo en un restaurante, donde la preparación de la comida no depende de usted. Dudoso, accede, sin embargo, en su mente ronda la siguiente pregunta ¿cómo puedo tener la certeza de que se seguirán los procedimientos adecuados para que la comida sea de calidad? Pues, estimado lector, es esta misma pregunta la que está a la base de la generación de conocimiento cientifico.

La ciencia, al igual que la cocina, no se trata solamente de los productos. Un plato de comida no aparece por arte de magia, sino que requiere el seguimiento riguroso de una receta. Usar los ingredientes adecuados, los gramajes adecuados y seguir los tiempos de cocción que dicta la receta no solo contribuyen a preparar un buen plato de comida, sino que hacen posible que ese plato pueda ser reproducido cada vez que sea necesario. Entonces, como buenos chefs que somos, la respuesta a la pregunta no es tan compleja: necesitamos ser capaces de evaluar el proceso de preparación de la comida para asegurarnos de que es el adecuado. Dicho de otro modo, el proceso de preparación debe ser transparente y estar abierto al escrutinio. En el caso de la comida, que el restaurante cuente con una cocina abierta o construida en torno a ventanales bastaría para lograr este objetivo. Sin embargo, cuando vamos al campo de la ciencia ¿cómo logramos que esté abierta al escrutinio público?

Esta pregunta puede ser algo engañosa ¿acaso la ciencia no está ya abierta al escrutinio público? La narrativa actual pareciese sugerir que no. En el último tiempo ha primado el diagnostico de que la ciencia está viviendo una crisis, donde polemicas situaciones de falseamiento de datos y mala conducta académica han salido a la luz. Uno de los casos más emblematicos es el de Diderik Stapel, un psicologo social considerado durante mucho tiempo un _rockstar_ en su campo: una figura de alto estatus, bastante influyente y con una producción académica impresionante cualitativa y cuantitativamente hablando. No obstante, en su caso, al igual que en muchos otros, se confirmó su autoría en una seríe de prácticas de investigación poco éticas, lo cuál terminó por acabar con su carrera y la retracción de 58 artículos.

Si bien casos de falseamiento o fabricación intencional de datos existen, no son las situaciones más comunes. Uno de los puntos principales de preocupación dentro de la investigación cientifica son las _prácticas cuestionables de investigación_, las cuáles tienen por consecuencia la generación de una ciencia irreproducible y sesgada.

Cualquier lector que se dedique a la inevstigación en ciencia sociales estará de acuerdo que la generación de conocimiento relacionado a lo social es una de nuestras principales contribuciones a la sociedad, si es que no la más grande. Es la tarea de los cientificos sociales el contribuir al bienestar de la sociedad por la vía de las herramientas de investigación. Es por eso que, para el caso especifico de las ciencias sociales, los efectos de una crisis de reproducibilidad son perjudiciales tanto para el desarrollo de la discplina como para la sociedad en su conjunto, ya que implica que la credibilidad de los hallazgos y su uso práctico para orientar la elaboración de políticas públicas empieza a ser puesto en duda. Actualmente, muchos tomadores de decisión no creen que la evidencia planteada por las ciencias sociales sean evidencia confiable. Es necesario tomar cartas en el asunto y volver a darle la credibilidad a las cienicas sociales.

Estimado investigador o investigadora de las ciencias sociales, este documento va dirijido a usted. Independiente de su discplina, de su trayectoria académica o de su conocimiento previo con respecto a estas temáticas, en este manual tenemos dos simples objetivos. El primero es que usted pueda convencerse de que, efectivamente, es necesario dar un giro en la forma que hacemos ciencia actualmente y que la adopción de prácticas relacionadas a la ciencia abierta son el primer paso en ese giro. El segundo es poder instruirlo en esa adopción de prácticas, particularmente en lo que respecta a dos conceptos centrales de la ciencia abierta: la transparencia y la reproducibilidad.

Si seguimos la metafora de la cocina que planteamos en un principio, la transparencia y la reproducibilidad son dos conceptos similares, pero no identicos. La transparencia implicaría la posibilidad de evaluar y poner en discusión la receta y la ejecución de la misma. En cambio, la reproducibilidad apuntaría a que la receta sea lo suficientemente clara y precisa para que el mismo plato, con el mismo sabor, pueda ser preparado por cualquier persona que contase con los ingredentes y recursos necesarios. En el campo de las ciencias, esta distinción la hacemos entre: 1) la transparencia en los diseños de investigación y 2) la reproducibilidad de los análisis en los artículos. Este manual estará estructurado en torno a estas dos dimensiones.

En la primera dimensión, haremos un barrido un tanto más detallado sobre la crisis de la reproducibilidad que aquí hemos mencionado brevemente. Ahondaremos en los factores que contribuyen a su reproducción, a las razones éticas por el cuales es necesario hacer un cambio y en las recomendaciones que se puedens seguir para adoptar ciertos principios de transparencia. En la segunda dimensión, nos centraremos en los análisis reproducibles, teniendo un caracter mucho más práctico. Presentaremos las distintas consideraciones que hay que tener para que un análisis sea fácilmente reproducible, desde tipos de flujos de trabajo hasta herramientas especificas que fomentan la reproducibilidad de los análisis.

Al final de este manual, ud. será capaz tanto de argumentar por qué la transparencia y la reproducibilidad son un paso importante en el avance de las ciencia sociales, asi como también contará con una serie de herramientas para llevar esto al quehacer académico del día a día.
